# Copyright (C) 2016 b20yang 
# ---
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option) any
# later version.

# This program is distributed in the hope that it will be useful,but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
################################################################################
include ../rules.mk

LIB_SMLD_HOOK_SRC = smld_hash.c
LIB_SMLD_HOOK_SRC+= smld_hook.c

LIB_SMLD_SRC+= smld.c
LIB_SMLD_OBJ=$(LIB_SMLD_SRC:.c=.o)

all: $(LIB_SMLD) $(LIB_SMLD_HOOK)

$(LIB_SMLD_HOOK): $(LIB_SMLD_HOOK_SRC) 
	$(CC) $(CFLAGS_GLOBAL) -shared -fPIC $? -o $(LIB_SMLD_HOOK) $(LDFLAGS_GLOBAL)

$(LIB_SMLD): $(LIB_SMLD_OBJ)
	$(AR) rcs $(LIB_SMLD) $? 

$(LIB_SMLD_OBJ): $(LIB_SMLD_SRC)
	$(CC) $(CFLAGS_GLOBAL) -c -o $(?:.c=.o) $?

clean:
	$(RM) $(LIB_SMLD) $(LIB_SMLD_HOOK) $(LIB_SMLD_OBJ) 
